'use client'

import { useState, useRef, useEffect } from 'react'
import Link from 'next/link'
import { Navbar } from '../components/Navbar'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

gsap.registerPlugin(ScrollTrigger)

// ─── THEME TOKENS ────────────────────────────────────────────────────────────
const T = {
    bgBase: '#010308',
    bgAlt: '#030612',
    bgEq: '#080E1C',
    bgExpl: '#0B132B',
    border: '#1E2D4A',
    textPri: '#FFFFFF',
    textSec: '#A3B8CC',
    cyan: '#00E5FF',
    green: '#00FF66',
    red: '#FF3333'
}

// ─── NOMENCLATURE DICTIONARY ─────────────────────────────────────────────────
const DICT = {
    // 1: Dynamics
    m: { sym: 'm', def: 'Quadrotor Mass', unit: 'kg', desc: 'Total mass of the physical drone.' },
    v_dot: { sym: 'v̇', def: 'Translational Acceleration', unit: 'm/s²', desc: 'Rate of change of velocity vector.' },
    g_vec: { sym: 'g', def: 'Gravity Vector', unit: 'm/s²', desc: 'Downward gravitational acceleration [0, 0, -9.81].' },
    R_q: { sym: 'R(q)', def: 'Rotation Matrix', unit: '—', desc: 'Maps body frame to world frame using quaternion q.' },
    f_T: { sym: 'f_T', def: 'Total Thrust', unit: 'N', desc: 'Combined upward force from all four rotors.' },
    f_wind: { sym: 'f_wind', def: 'Wind Disturbance', unit: 'N', desc: 'Stochastic external force applied to the drone body.' },
    J: { sym: 'J', def: 'Inertia Matrix', unit: 'kg·m²', desc: 'Resistance to rotational acceleration about the 3 body axes.' },
    w_dot: { sym: 'ω̇', def: 'Angular Acceleration', unit: 'rad/s²', desc: 'Rate of change of the body rotation rates.' },
    w: { sym: 'ω', def: 'Angular Velocity', unit: 'rad/s', desc: 'Current rotational rates [roll, pitch, yaw].' },
    cross_op: { sym: '×', def: 'Cross Product', unit: '—', desc: 'Computes gyroscopic torque induced by rotating frame.' },
    tau: { sym: 'τ', def: 'Control Torque', unit: 'N·m', desc: 'Rotational moments generated by differential rotor speeds.' },

    // 2: Formulation
    s_t: { sym: 's_t', def: 'State Vector', unit: '—', desc: 'Complete mathematical description of the system at time t.' },
    p_t: { sym: 'p_t', def: 'Position', unit: 'm', desc: 'Absolute 3D Cartesian coords [x, y, z].' },
    v_t: { sym: 'v_t', def: 'Linear Velocity', unit: 'm/s', desc: 'Current speed vector.' },
    q_t: { sym: 'q_t', def: 'Attitude Quaternion', unit: '—', desc: 'Gimbal-lock-free 3D orientation.' },
    w_t: { sym: 'w_t', def: 'Wind State', unit: 'm/s', desc: 'Latent representation of current external turbulence.' },
    a_t: { sym: 'a_t', def: 'Action Vector', unit: '—', desc: 'Normalized control effort [-1, 1] mapped to motors.' },
    T_act: { sym: 'T', def: 'Collective Thrust', unit: 'N', desc: 'Baseline lift generated by all motors equally.' },
    tau_phi: { sym: 'τ_φ', def: 'Roll Torque', unit: 'N·m', desc: 'Differential thrust between left/right rotors.' },
    tau_theta: { sym: 'τ_θ', def: 'Pitch Torque', unit: 'N·m', desc: 'Differential thrust between front/back rotors.' },
    tau_psi: { sym: 'τ_ψ', def: 'Yaw Torque', unit: 'N·m', desc: 'Differential drag caused by clockwise vs counter-clockwise rotors.' },

    // 3: PPO
    pi_theta: { sym: 'π_θ(a|s)', def: 'Stochastic Policy', unit: '—', desc: 'Probability distribution over control actions.' },
    N_dist: { sym: '𝒩', def: 'Normal Distribution', unit: '—', desc: 'Continuous probability distribution parameterized by mean and covariance.' },
    mu_theta: { sym: 'μ_θ(s)', def: 'Mean Action', unit: '—', desc: 'Primary deterministic control effort output by the actor network.' },
    Sigma_theta: { sym: 'Σ_θ(s)', def: 'Covariance Matrix', unit: '—', desc: 'Exploration spread; shrinks mathematically as the agent learns.' },
    V_phi: { sym: 'V_φ(s)', def: 'Value Function', unit: '—', desc: 'Critic network predicting expected future return.' },
    J_theta: { sym: 'J(θ)', def: 'Optimization Objective', unit: '—', desc: 'Expected discounted return the RL algorithm directly maximizes.' },
    gamma: { sym: 'γ', def: 'Discount Factor', unit: '—', desc: 'Weight of future rewards vs immediate (typically 0.99).' },
    L_CLIP: { sym: 'L^CLIP(θ)', def: 'PPO Surrogate Objective', unit: '—', desc: 'Clipped loss function ensuring stable, monotonic policy improvements.' },

    // 4: Reward
    R_t: { sym: 'R_t', def: 'Instantaneous Reward', unit: '—', desc: 'Scalar feedback directly driving optimization behavior.' },
    alpha_1: { sym: 'α₁', def: 'Rate Penalty Weight', unit: '—', desc: 'Scaling factor discouraging angular jitter.' },
    norm_w: { sym: '||ω||²', def: 'Angular Kinetic Energy', unit: '(rad/s)²', desc: 'Quadratic penalty on fast body rotations.' },
    alpha_2: { sym: 'α₂', def: 'Position Weight', unit: '—', desc: 'Scaling factor enforcing strict hover constraints.' },
    norm_ep: { sym: '||e_p||²', def: 'Position Error squared', unit: 'm²', desc: 'Quadratic distance from the target origin.' },
    alpha_3: { sym: 'α₃', def: 'Attitude Weight', unit: '—', desc: 'Scaling factor enforcing flat hover orientation.' },
    norm_eatt: { sym: '||e_att||²', def: 'Attitude Error squared', unit: 'rad²', desc: 'Quadratic deviation from pitch/roll = 0.' },
    alpha_4: { sym: 'α₄', def: 'Effort Weight', unit: '—', desc: 'Scaling factor preventing aggressive banging on the motors.' },
    norm_a: { sym: '||a_t||²', def: 'Action Magnitude squared', unit: '—', desc: 'Quadratic penalty on large network outputs.' },
    E_R: { sym: 'E[R_t]', def: 'Expected Reward', unit: '—', desc: 'Mean episodic return over training.' },
    Var_w: { sym: 'Var(||ω||)', def: 'Angular Variance', unit: '—', desc: 'Statistical spread of rotational vibration.' },

    // 5: Learning Dynamics
    theta_k: { sym: 'θ_k', def: 'Current Weights', unit: '—', desc: 'Policy neural network weights before gradient step.' },
    eta: { sym: 'η', def: 'Learning Rate', unit: '—', desc: 'Step size multiplier for gradient ascent operations.' },
    grad_L: { sym: '∇_θ L^CLIP', def: 'Policy Gradient', unit: '—', desc: 'Direction of steepest improvement subject to clip constraints.' },
    M_theta: { sym: 'M(θ)', def: 'Performance Metric', unit: '—', desc: 'Expected quadratic error summarizing stabilization capability.' },

    // 6: Domain Randomization
    w_t_dist: { sym: 'w_t ~ D_train', def: 'Wind Sampling', unit: '—', desc: 'Disturbances are drawn from a randomized domain.' },
    theta_star: { sym: 'θ*', def: 'Optimal Weights', unit: '—', desc: 'Convergence point providing distributionally robust stabilization.' },

    // 7: Metrics
    S_i: { sym: 'S_i', def: 'Regime Score', unit: '—', desc: 'Time-averaged error under specific stochastic wind condition i.' },

    // 8: Lyapunov
    e_p: { sym: 'e_p', def: 'Position Error', unit: 'm', desc: 'Spatial deviation from the stable hover equilibrium.' },
    p: { sym: 'p', def: 'Current Position', unit: 'm', desc: 'Drone spatial center of mass coordinates.' },
    p_ref: { sym: 'p_ref', def: 'Reference Target', unit: 'm', desc: 'Desired operating point.' },
    e_w: { sym: 'e_ω', def: 'Angular Velocity Error', unit: 'rad/s', desc: 'Deviation from zero rotation.' },
    omega: { sym: 'ω', def: 'Angular Velocity', unit: 'rad/s', desc: 'Current body rotation rates.' },
    phi: { sym: 'φ', def: 'Roll Angle', unit: 'rad', desc: 'Lateral drone tilt.' },
    theta: { sym: 'θ', def: 'Pitch Angle', unit: 'rad', desc: 'Longitudinal drone tilt.' },
    e_att: { sym: 'e_att', def: 'Attitude Error Vector', unit: 'rad', desc: 'Stacked roll and pitch deviations from flat.' },
    V_e: { sym: 'V(e)', def: 'Lyapunov Candidate', unit: 'J', desc: 'Artificial energy landscape; reaching global minimum guarantees stability.' },
    e_p_T: { sym: 'e_pᵀ', def: 'Transpose Operator', unit: '—', desc: 'Creates the quadratic spatial energy form.' },
    e_w_T: { sym: 'e_ωᵀ', def: 'Transpose Operator', unit: '—', desc: 'Creates the rotational kinetic energy form.' },
    e_att_T: { sym: 'e_attᵀ', def: 'Transpose Operator', unit: '—', desc: 'Creates the rotational potential energy form.' },
    e_T: { sym: 'eᵀ', def: 'Combined Error Transpose', unit: '—', desc: 'Full vector of system errors.' },
    V_dot: { sym: 'V̇', def: 'Lyapunov Derivative', unit: 'W', desc: 'Time rate of energy change. Must be negative to converge.' },
    K_w: { sym: 'K_ω', def: 'Angular Damping Gain', unit: '—', desc: 'Positive definite matrix bleeding rotational kinetic energy.' },
    K_p: { sym: 'K_p', def: 'Trans. Stiffness Gain', unit: '—', desc: 'Positive definite matrix providing spatial restoring force.' },
    K_att: { sym: 'K_att', def: 'Rot. Stiffness Gain', unit: '—', desc: 'Positive definite matrix providing attitude restoring torque.' }
}


// ─── COMPONENTS ──────────────────────────────────────────────────────────────


function HoverVar({ id, children, hoverId, setHover, color = '#F8FAFC' }) {
    const isHovered = hoverId === id
    const isFaded = hoverId !== null && hoverId !== id

    return (
        <span
            onMouseEnter={() => setHover(id)}
            onMouseLeave={() => setHover(null)}
            style={{
                color: isHovered ? T.cyan : (isFaded ? T.textSec : color),
                padding: '0 6px',
                cursor: 'crosshair',
                transition: 'all 0.2s ease',
                display: 'inline-flex',
                alignItems: 'center',
                fontWeight: isHovered ? 500 : 400
            }}
        >
            {children}
        </span>
    )
}

function SectionWrapper({ children, bg, id }) {
    return (
        <section id={id} className="tech-section" style={{
            background: bg,
            borderTop: `1px solid ${T.border}`,
            padding: '120px 0',
            minHeight: '85vh',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center'
        }}>
            <div style={{ width: '100%', maxWidth: 1200, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 80, alignItems: 'center' }}>
                {children}
            </div>
        </section>
    )
}

// ─── MAIN PAGE ───────────────────────────────────────────────────────────────

export default function MathematicalConsole() {
    const [h, setH] = useState(null) // Global hover state
    const [panelData, setPanelData] = useState(null) // Keeps the last hovered item so that fade down is smooth

    useEffect(() => {
        gsap.utils.toArray('.tech-step').forEach(el => {
            gsap.fromTo(el, { opacity: 0, y: 12 }, {
                opacity: 1, y: 0, duration: 0.6, ease: 'power1.out',
                scrollTrigger: { trigger: el, start: 'top 85%' }
            })
        })
    }, [])

    useEffect(() => {
        if (h && DICT[h]) {
            setPanelData(DICT[h])
        }
    }, [h])

    return (
        <div style={{ background: T.bgBase, color: T.textPri, minHeight: '100vh', fontFamily: 'sans-serif', paddingTop: 72 }}>
            <Navbar activePath="/technical" />

            {/* FLOATING HOVER PANEL (Fixed relative to center column) */}
            <div
                style={{
                    position: 'fixed',
                    left: '50%',
                    marginLeft: 440, // Centered 800px block ends at 400. 40px gap.
                    top: '50%',
                    transform: 'translateY(-50%)',
                    width: 280,
                    background: T.bgExpl,
                    border: `1px solid ${T.border}`,
                    padding: panelData ? 18 : 0, // Only pad if we have ever had data
                    opacity: h ? 1 : 0,
                    pointerEvents: 'none',
                    transition: 'opacity 0.2s ease, padding 0.2s ease',
                    zIndex: 9999,
                    boxShadow: '0 20px 40px rgba(0,0,0,0.4)',
                    backdropFilter: 'blur(10px)',
                    borderRadius: 4
                }}
            >
                {panelData && (
                    <>
                        <div style={{ color: T.cyan, fontFamily: 'monospace', fontSize: '1.2rem', marginBottom: 8, borderBottom: `1px solid ${T.border}`, paddingBottom: 8 }}>
                            {panelData.sym}
                        </div>
                        <div style={{ fontSize: '0.9rem', color: T.textPri, fontWeight: 500, marginBottom: 4 }}>{panelData.def}</div>
                        {panelData.unit !== '—' && (
                            <div style={{ fontSize: '0.8rem', color: T.textSec, fontFamily: 'monospace', marginBottom: 12 }}>[{panelData.unit}]</div>
                        )}
                        <div style={{ fontSize: '0.85rem', color: T.textSec, lineHeight: 1.5 }}>
                            {panelData.desc}
                        </div>
                    </>
                )}
            </div>

            {/* 1. QUADROTOR DYNAMICS */}
            <SectionWrapper id="dynamics" bg={T.bgBase}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>01 — Quadrotor Dynamics</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>Translational & Rotational Equations</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>
                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px 60px', fontFamily: 'monospace', fontSize: '2rem', display: 'flex', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="m" hoverId={h} setHover={setH}>m</HoverVar>
                        <HoverVar id="v_dot" hoverId={h} setHover={setH}>v̇</HoverVar> =
                        <HoverVar id="m" hoverId={h} setHover={setH}>m</HoverVar>
                        <HoverVar id="g_vec" hoverId={h} setHover={setH} color={T.cyan}>g</HoverVar> +
                        <HoverVar id="R_q" hoverId={h} setHover={setH}>R(q)</HoverVar>
                        <HoverVar id="f_T" hoverId={h} setHover={setH}>f_T</HoverVar> +
                        <HoverVar id="f_wind" hoverId={h} setHover={setH} color={T.red}>f_wind</HoverVar>
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px 60px', fontFamily: 'monospace', fontSize: '2rem', display: 'flex', alignItems: 'center', justifyContent: 'center', flexWrap: 'wrap', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="J" hoverId={h} setHover={setH}>J</HoverVar>
                        <HoverVar id="w_dot" hoverId={h} setHover={setH}>ω̇</HoverVar> +
                        <HoverVar id="w" hoverId={h} setHover={setH}>ω</HoverVar>
                        <HoverVar id="cross_op" hoverId={h} setHover={setH}>×</HoverVar> (
                        <HoverVar id="J" hoverId={h} setHover={setH}>J</HoverVar>
                        <HoverVar id="w" hoverId={h} setHover={setH}>ω</HoverVar> ) =
                        <HoverVar id="tau" hoverId={h} setHover={setH} color={T.cyan}>τ</HoverVar>
                    </div>

                    <div style={{ background: T.bgExpl, border: `1px solid ${T.border}`, padding: 32, width: '100%', maxWidth: 800, textAlign: 'center', lineHeight: 1.8, color: T.textSec }}>
                        The quadrotor's motion is governed by non-linear rigid body dynamics. Translational motion is driven by collective thrust mapped through the attitude rotation matrix, heavily perturbed by stochastic wind. Rotational motion accounts for complex gyroscopic coupling effects inherent to 3D rotation, requiring precise torque actuation to maintain stability.
                    </div>
                </div>
            </SectionWrapper>


            {/* 2. STATE & CONTROL FORMULATION */}
            <SectionWrapper id="state-formulation" bg={T.bgAlt}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>02 — State & Control Formulation</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>State Vectors and Actions</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>
                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '2.2rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="s_t" hoverId={h} setHover={setH} color={T.cyan}>s_t</HoverVar> = [
                        <HoverVar id="p_t" hoverId={h} setHover={setH}>p_t</HoverVar>,
                        <HoverVar id="v_t" hoverId={h} setHover={setH}>v_t</HoverVar>,
                        <HoverVar id="q_t" hoverId={h} setHover={setH}>q_t</HoverVar>,
                        <HoverVar id="w_t" hoverId={h} setHover={setH}>ω_t</HoverVar>,
                        <HoverVar id="w_t" hoverId={h} setHover={setH} color={T.red}>w_t</HoverVar> ]
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '2.2rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="a_t" hoverId={h} setHover={setH} color={T.cyan}>a_t</HoverVar> = [
                        <HoverVar id="T_act" hoverId={h} setHover={setH}>T</HoverVar>,
                        <HoverVar id="tau_phi" hoverId={h} setHover={setH}>τ_φ</HoverVar>,
                        <HoverVar id="tau_theta" hoverId={h} setHover={setH}>τ_θ</HoverVar>,
                        <HoverVar id="tau_psi" hoverId={h} setHover={setH}>τ_ψ</HoverVar> ]
                    </div>

                    <div style={{ background: T.bgExpl, border: `1px solid ${T.border}`, padding: 32, width: '100%', maxWidth: 800, textAlign: 'center', lineHeight: 1.8, color: T.textSec }}>
                        We employ full-state feedback. The agent receives absolute spatial coordinates, velocities, and attitude quaternions, alongside a latent representation of the turbulent wind state. It outputs continuous, bounded actions representing collective thrust and individual rotational torques.
                    </div>
                </div>
            </SectionWrapper>


            {/* 3. PPO POLICY STRUCTURE */}
            <SectionWrapper id="ppo" bg={T.bgBase}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>03 — Optimization Engine</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>PPO Policy Structure</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '2rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="pi_theta" hoverId={h} setHover={setH} color={T.cyan}>π_θ(a|s)</HoverVar> = <HoverVar id="N_dist" hoverId={h} setHover={setH}>𝒩</HoverVar>( <HoverVar id="mu_theta" hoverId={h} setHover={setH}>μ_θ(s)</HoverVar>, <HoverVar id="Sigma_theta" hoverId={h} setHover={setH}>Σ_θ(s)</HoverVar> )
                    </div>
                    <div style={{ color: T.textSec, fontSize: '0.9rem', textAlign: 'center' }}>The actor network outputs a Gaussian distribution for continuous exploration.</div>

                    <div style={{ height: 1, width: 200, background: T.border }} />

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '2rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="V_phi" hoverId={h} setHover={setH} color={T.green}>V_φ(s)</HoverVar>
                    </div>
                    <div style={{ color: T.textSec, fontSize: '0.9rem', textAlign: 'center' }}>The critic network predicts expected future stabilization capability.</div>

                    <div style={{ height: 1, width: 200, background: T.border }} />

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '1.8rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="J_theta" hoverId={h} setHover={setH}>J(θ)</HoverVar> = E[ Σ <HoverVar id="gamma" hoverId={h} setHover={setH}>γ</HoverVar>ᵀ <HoverVar id="R_t" hoverId={h} setHover={setH}>R_t</HoverVar> ]
                    </div>
                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="L_CLIP" hoverId={h} setHover={setH} color={T.cyan}>L^CLIP(θ)</HoverVar> = E[ min( r_t(θ)Â_t , clip(...) ) ]
                    </div>
                    <div style={{ background: T.bgExpl, border: `1px solid ${T.border}`, padding: 32, width: '100%', maxWidth: 800, textAlign: 'center', lineHeight: 1.8, color: T.textSec }}>
                        Proximal Policy Optimization maximizes long-term discounted rewards while binding updates with a trust region penalty, preventing catastrophic unlearning during volatile aerodynamic moments.
                    </div>

                </div>
            </SectionWrapper>


            {/* 4. REWARD FUNCTION DESIGN */}
            <SectionWrapper id="reward" bg={T.bgAlt}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>04 — Implicit CLF Design</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>Reward Function Design</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 1000, display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 8, lineHeight: 2 }}>
                        <HoverVar id="R_t" hoverId={h} setHover={setH}>R_t</HoverVar> =
                        <span style={{ color: T.textSec, marginLeft: 8 }}>−</span> <HoverVar id="alpha_1" hoverId={h} setHover={setH}>α₁</HoverVar> <HoverVar id="norm_w" hoverId={h} setHover={setH} color={T.red}>||ω||²</HoverVar>
                        <span style={{ color: T.textSec, marginLeft: 8 }}>−</span> <HoverVar id="alpha_2" hoverId={h} setHover={setH}>α₂</HoverVar> <HoverVar id="norm_ep" hoverId={h} setHover={setH} color={T.cyan}>||e_p||²</HoverVar>
                        <span style={{ color: T.textSec, marginLeft: 8 }}>−</span> <HoverVar id="alpha_3" hoverId={h} setHover={setH}>α₃</HoverVar> <HoverVar id="norm_eatt" hoverId={h} setHover={setH} color={T.red}>||e_att||²</HoverVar>
                        <span style={{ color: T.textSec, marginLeft: 8 }}>−</span> <HoverVar id="alpha_4" hoverId={h} setHover={setH}>α₄</HoverVar> <HoverVar id="norm_a" hoverId={h} setHover={setH} color={'#64748B'}>||a_t||²</HoverVar>
                    </div>

                    <div style={{ display: 'flex', gap: 40, width: '100%', maxWidth: 800 }}>
                        <div style={{ flex: 1, border: `1px solid ${T.border}`, background: T.bgEq, padding: 32, textAlign: 'center' }}>
                            <HoverVar id="E_R" hoverId={h} setHover={setH} color={T.green}>E[R_t]</HoverVar>
                            <span style={{ color: T.green, fontSize: '2rem', marginLeft: 16 }}>↑</span>
                        </div>
                        <div style={{ flex: 1, border: `1px solid ${T.border}`, background: T.bgEq, padding: 32, textAlign: 'center' }}>
                            <HoverVar id="Var_w" hoverId={h} setHover={setH} color={T.cyan}>Var(||ω||)</HoverVar>
                            <span style={{ color: T.cyan, fontSize: '2rem', marginLeft: 16 }}>↓</span>
                        </div>
                    </div>

                    <div style={{ color: T.textSec, fontSize: '1.2rem', fontWeight: 300, textAlign: 'center' }}>
                        “Training reduces instability and improves control smoothness.”
                    </div>

                </div>
            </SectionWrapper>

            {/* 5. LEARNING DYNAMICS */}
            <SectionWrapper id="dynamics" bg={T.bgBase}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>05 — Parameter Tracking</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>Learning Dynamics Over 600K Steps</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>
                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '2rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="theta_k" hoverId={h} setHover={setH}>θ_k+1</HoverVar> = θ_k + <HoverVar id="eta" hoverId={h} setHover={setH} color={T.cyan}>η</HoverVar> <HoverVar id="grad_L" hoverId={h} setHover={setH}>∇_θ L^CLIP</HoverVar>
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="M_theta" hoverId={h} setHover={setH}>M(θ)</HoverVar> = E[ ||ω||² + ||e_p||² ]
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.8rem', textAlign: 'center', width: '100%', maxWidth: 800, color: T.green }}>
                        M(θ_600k) &lt; M(θ_100k) &lt; M(θ_0)
                    </div>

                    <div style={{ color: T.textSec, fontSize: '1.2rem', fontWeight: 300, textAlign: 'center' }}>
                        “Monotonic reduction in stabilization error over 600k gradient ascent steps.”
                    </div>
                </div>
            </SectionWrapper>


            {/* 6. DOMAIN RANDOMIZATION */}
            <SectionWrapper id="randomization" bg={T.bgAlt}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>06 — Training Distribution</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>Domain Randomization</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>
                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '2rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="w_t_dist" hoverId={h} setHover={setH} color={T.cyan}>w_t ~ D_train</HoverVar>
                    </div>

                    <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
                        {['Calm', 'Smooth', 'Strong', 'Mixed'].map(dist => (
                            <div key={dist} style={{ border: `1px solid ${T.border}`, padding: '12px 24px', fontSize: '1.2rem', color: T.textSec, background: T.bgExpl }}>
                                {dist}
                            </div>
                        ))}
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="theta_star" hoverId={h} setHover={setH} color={T.green}>θ*</HoverVar> = arg min_θ E_w[ <HoverVar id="M_theta" hoverId={h} setHover={setH}>M(θ)</HoverVar> ]
                    </div>

                    <div style={{ color: T.textSec, fontSize: '1.2rem', fontWeight: 300, textAlign: 'center' }}>
                        “Policy optimized for minimal expected error across all disturbance regimes simultaneously.”
                    </div>
                </div>
            </SectionWrapper>


            {/* 7. FINAL METRICS */}
            <SectionWrapper id="metrics" bg={T.bgBase}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>07 — System Validation</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>Final Performance Metrics</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="S_i" hoverId={h} setHover={setH} color={T.cyan}>S_i</HoverVar> = (1/T) Σ ( ||ω_t||² + ||e_p||² )
                    </div>

                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, width: '100%', maxWidth: 800 }}>
                        {[
                            { l: 'S_calm', v: 15 },
                            { l: 'S_smooth', v: 30 },
                            { l: 'S_strong', v: 80, hl: true },
                            { l: 'S_mixed', v: 50 }
                        ].map(s => (
                            <div key={s.l} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
                                <div style={{ color: s.hl ? T.cyan : T.textSec, fontSize: '1.2rem' }}>{s.l}</div>
                                <div style={{ width: '100%', height: 4, background: T.border, position: 'relative' }}>
                                    <div style={{ position: 'absolute', left: 0, bottom: 0, top: 0, width: `${s.v}%`, background: s.hl ? T.cyan : T.textSec }} />
                                </div>
                            </div>
                        ))}
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.8rem', textAlign: 'center', width: '100%', maxWidth: 800, color: T.green }}>
                        S_strong^600k &lt; S_strong^early
                    </div>

                    <div style={{ display: 'flex', gap: 40, width: '100%', maxWidth: 800 }}>
                        <div style={{ flex: 1, border: `1px solid ${T.border}`, background: T.bgEq, padding: 32, textAlign: 'center', fontFamily: 'monospace', fontSize: '1.4rem' }}>
                            <span style={{ color: T.green }}>E[R_i^600k] &gt; E[R_i^100k]</span>
                        </div>
                        <div style={{ flex: 1, border: `1px solid ${T.border}`, background: T.bgEq, padding: 32, textAlign: 'center', fontFamily: 'monospace', fontSize: '1.4rem' }}>
                            <span style={{ color: T.cyan }}>Var(R_i) ↓</span>
                        </div>
                    </div>

                    <div style={{ color: T.textSec, fontSize: '1.2rem', fontWeight: 300, textAlign: 'center' }}>
                        “Significantly improved worst-case performance and reduced reward variability.”
                    </div>
                </div>
            </SectionWrapper>


            {/* 8. LYAPUNOV STABILITY */}
            <SectionWrapper id="lyapunov" bg={T.bgAlt}>
                <div className="tech-step" style={{ textAlign: 'center' }}>
                    <p className="font-mono uppercase" style={{ fontSize: 10, letterSpacing: '4px', color: T.textSec, marginBottom: 16 }}>08 — Theoretical Guarantee</p>
                    <h2 style={{ fontSize: '2.5rem', fontWeight: 400, color: T.textPri }}>Lyapunov Stability Interpretation</h2>
                </div>

                <div className="tech-step" style={{ display: 'flex', flexDirection: 'column', gap: 40, width: '100%', alignItems: 'center' }}>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '32px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="e_p" hoverId={h} setHover={setH}>e_p</HoverVar> = <HoverVar id="p" hoverId={h} setHover={setH}>p</HoverVar> − <HoverVar id="p_ref" hoverId={h} setHover={setH}>p_ref</HoverVar>  |  <HoverVar id="e_w" hoverId={h} setHover={setH}>e_ω</HoverVar> = <HoverVar id="omega" hoverId={h} setHover={setH}>ω</HoverVar> |  <HoverVar id="e_att" hoverId={h} setHover={setH}>e_att</HoverVar> = [ <HoverVar id="phi" hoverId={h} setHover={setH}>φ</HoverVar> ; <HoverVar id="theta" hoverId={h} setHover={setH}>θ</HoverVar> ]
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.8rem', textAlign: 'center', width: '100%', maxWidth: 800 }}>
                        <HoverVar id="V_e" hoverId={h} setHover={setH} color={T.cyan}>V(e)</HoverVar> = ½ <HoverVar id="e_p_T" hoverId={h} setHover={setH}>e_pᵀ</HoverVar> <HoverVar id="e_p" hoverId={h} setHover={setH}>e_p</HoverVar> + ½ <HoverVar id="e_w_T" hoverId={h} setHover={setH}>e_ωᵀ</HoverVar> <HoverVar id="J" hoverId={h} setHover={setH}>J</HoverVar> <HoverVar id="e_w" hoverId={h} setHover={setH}>e_ω</HoverVar> + ½ <HoverVar id="e_att_T" hoverId={h} setHover={setH}>e_attᵀ</HoverVar> <HoverVar id="e_att" hoverId={h} setHover={setH}>e_att</HoverVar>
                    </div>

                    <div style={{ background: T.bgEq, border: `1px solid ${T.border}`, padding: '40px', fontFamily: 'monospace', fontSize: '1.6rem', textAlign: 'center', width: '100%', maxWidth: 800, lineHeight: 1.8 }}>
                        <HoverVar id="V_dot" hoverId={h} setHover={setH}>V̇</HoverVar> =
                        <span style={{ color: T.green }}> − <HoverVar id="e_w_T" hoverId={h} setHover={setH} color={T.green}>e_ωᵀ</HoverVar> <HoverVar id="K_w" hoverId={h} setHover={setH} color={T.green}>K_ω</HoverVar> <HoverVar id="e_w" hoverId={h} setHover={setH} color={T.green}>e_ω</HoverVar> </span>
                        <span style={{ color: T.green }}> − <HoverVar id="e_p_T" hoverId={h} setHover={setH} color={T.green}>e_pᵀ</HoverVar> <HoverVar id="K_p" hoverId={h} setHover={setH} color={T.green}>K_p</HoverVar> <HoverVar id="e_p" hoverId={h} setHover={setH} color={T.green}>e_p</HoverVar> </span>
                        <span style={{ color: T.green }}> − <HoverVar id="e_att_T" hoverId={h} setHover={setH} color={T.green}>e_attᵀ</HoverVar> <HoverVar id="K_att" hoverId={h} setHover={setH} color={T.green}>K_att</HoverVar> <HoverVar id="e_att" hoverId={h} setHover={setH} color={T.green}>e_att</HoverVar> </span>
                        + <span style={{ color: T.red }}> <HoverVar id="e_T" hoverId={h} setHover={setH} color={T.red}>eᵀ</HoverVar> <HoverVar id="f_wind" hoverId={h} setHover={setH} color={T.red}>f_wind</HoverVar> </span>
                    </div>

                    <div style={{ background: T.bgExpl, border: `1px solid ${T.border}`, padding: 32, width: '100%', maxWidth: 800, textAlign: 'center', lineHeight: 1.8, color: T.cyan, fontSize: '1.6rem', fontWeight: 300 }}>
                        “PPO implicitly learns a nonlinear Lyapunov-stabilizing feedback controller.”
                    </div>
                </div>
            </SectionWrapper>

        </div>
    )
}
